### ISSUE TITLE
Do you want an update ? 

### ISSUE THREAD

**Issue by julien-leclercq** [revery-ui/revery-quick-start-ocaml#1]
Hello, 
I wanted to see how it worked in OCaml so I cloned the repo and got everything working, would you be interested in a PR or is this an abandoned repository ?

**Comment by glennsl** [comment]
Hey. This isn't exactly well-maintained, but I wouldn't say abandoned. And a PR bringing it up to date certainly couldn't hurt. So yes, please! :)

**Comment by glennsl** [comment]
Fixed by #2. Thanks @julien-leclercq!
